CREATE TABLE students (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(255),
    last_name VARCHAR2(255),
    email VARCHAR2(255) UNIQUE,
    enrollment_date DATE
);